apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.isBinary }}
  isBinary: {{ .Values.isBinary }}
  {{- end }}
  path: {{ .Values.vaultSecret.path | quote }}
  {{- with .Values.vaultSecret.keys }}
  keys:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.secretEngine }}
  secretEngine: {{ .Values.secretEngine | quote  }}
  {{- end }}
  type: {{ .Values.type | quote  }}
  {{- with .Values.templates }}
  templates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
